[tool.black]
skip-string-normalization = true

[tool.poetry]
name = "libvcs"
version = "0.4.4"
description = "vcs abstraction layer"
license = "MIT"
authors = ["Tony Narlock <tony@git-pull.com>"]

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"

[tool.poetry.dev-dependencies]
### Docs ###
sphinx = [
  {version="<2", python="<3"},
  {version="*", python=">=3"}
]
recommonmark = {version = "^0.6.0"}
alagitpull = {version = "^0.0.25-rc.2", allow-prereleases = true}
sphinx-issues = {version = "^1.2.0"}

### Testing ###
pytest = [
  {version="<4.7.0", python="<3"},
  {version="*", python=">=3"}
]
pathlib2 = {version="<2.3.5", python="<3"}  # Untangle pytest peer-dependency
pytest-rerunfailures = "*"
pytest-mock = [
  {version="<3.0.0", python="<3"},
  {version="*", python=">=3"}
]

### Coverage ###
codecov = "*"
coverage = "*"
pytest-cov = [
  {version="<2.10.0", python="<3"},
  {version="*", python=">=3"}
]

### Format ###
black = {version="==19.10b0", python="^3.6"}
isort = [
  {version="<5", python="<3.6"},
  {version="*", python=">=3.6"}
]

### Lint ###
flake8 = "*"

### Deploy ###
twine = "*"

### Gatsby Source ###
sphinx-autoapi = {version = "^1.4.0", python = ">=3.6"}
astroid = {version = "^2.4.2", python = ">=3.6"}
sphobjinv = {version = "^2.0.1", python = ">=3.5"}

[tool.poetry.extras]
docs = ["sphinx", "recommonmark", "sphinx-issues", "alagitpull"]
test = ["pytest", "pathlib2", "pytest-rerunfailures", "pytest-mock"]
coverage = ["codecov", "coverage", "pytest-cov"]
format = ["black", "isort"]
lint = ["flake8"]
deploy = ["deploy"]
gatsby = ["astroid", "sphinx-autoapi", "sphobjinv"]
